# This python file was generated by the javascript-to-python convertor.
# Github: https://github.com/jiricekcz/javascript-to-python
# Convertor author: https://github.com/jiricekcz
a=Exception("Error")
try: 
    raise a
except Exception as e: 
    pass
finally:
    pass