# This python file was generated by the javascript-to-python convertor.
# Github: https://github.com/jiricekcz/javascript-to-python
# Convertor author: https://github.com/jiricekcz
def fepyfyhyeukhotcyzyxjliojgmwfwdod(x):
    return "a"
def joikpqogscucnujlgkiqqtjphltlzqvv(x):
    return "b"
a=fepyfyhyeukhotcyzyxjliojgmwfwdod
a=joikpqogscucnujlgkiqqtjphltlzqvv
print(a())