# This python file was generated by the javascript-to-python convertor.
# Github: https://github.com/jiricekcz/javascript-to-python
# Convertor author: https://github.com/jiricekcz
a=(5)
b=(8)
c=(10)
print(f"a: {a}, b: {b}, c: {c}, d:{(a+b)}")